Repository sepang-pang/firstclass-msa-project, pull requests merged in 2024-12, with the labels that each got.

#11 허브 관리 기능 구현
  com.first-class.msa.hub/build.gradle
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/ResDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/ResHubPostDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/ResHubSearchDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/model/Hub.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/repository/HubRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/configuration/CacheConfig.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/configuration/QueryDslConfig.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubQueryBinder.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubRepositoryImpl.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/JpaHubRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/request/ReqHubPostDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/request/ReqHubPutByIdDTO.java
  com.first-class.msa.hub/src/main/resources/application.properties
  com.first-class.msa.hub/src/main/resources/application.yml
Labels: ✨ Feature

#14 gateway 권한 검증 기능 구현
  .idea/compiler.xml
  .idea/workspace.xml
  com.first-class.msa.agent/build.gradle
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/controller/UserController.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/dto/ReqLoginDTO.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/dto/ResLoginDTO.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/dto/ResUserPostDTO.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/service/UserDetailService.java
  com.first-class.msa.gateway/build.gradle
  com.first-class.msa.gateway/src/main/java/com/first_class/msa/gateway/CustomPostFilter.java
  com.first-class.msa.gateway/src/main/java/com/first_class/msa/gateway/CustomPreFilter.java
  com.first-class.msa.gateway/src/main/java/com/first_class/msa/gateway/JwtAuthorizationFilter.java
  com.first-class.msa.gateway/src/main/resources/application.yml
Labels: ✨ Feature

#21 권한 검증 요청 API 수정
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/controller/UserController.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/dto/ReqRoleValidationDTO.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/dto/ResRoleGetByIdDTO.java
  com.first-class.msa.auth/src/main/java/com/first_class/msa/auth/domain/service/UserService.java
Labels: 🔨 Refactor, 🌐 API, ✨ Feature

#25 업체 관리 기능 구현
  com.first-class.msa.business/.gitignore
  com.first-class.msa.business/build.gradle
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/BusinessApplication.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/dto/ResBusinessPostDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/dto/ResBusinessSearchDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/dto/ResRoleGetByUserIdDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/dto/SuccessResponseDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/service/BusinessService.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/domain/model/Business.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/domain/model/BusinessType.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/domain/model/RoleType.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/domain/repository/BusinessRepository.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/client/AuthClient.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/client/HubClient.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/configuration/CacheConfig.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/configuration/QueryDslConfig.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/repository/BusinessQueryRepository.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/repository/BusinessRepositoryImpl.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/repository/JpaBusinessRepository.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/presentation/controller/BusinessController.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/presentation/request/ReqBusinessPostDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/presentation/request/ReqBusinessPutByIdDTO.java
  com.first-class.msa.business/src/main/resources/application-dev.yml
  com.first-class.msa.business/src/main/resources/application.yml
  com.first-class.msa.hub/.gitignore
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/repository/HubRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubRepositoryImpl.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/JpaHubRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubController.java
  com.first-class.msa.hub/src/main/resources/application-dev.yml
  com.first-class.msa.hub/src/main/resources/application.yml
Labels: 🌐 API, ✨ Feature

#29 배송 당당자 기능구현
  com.first-class.msa.agent/build.gradle
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/AgentApplication.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/DeliveryAgentAuthSearchConditionDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResDeliveryAgentDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResDeliveryAgentSearchDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResGlobalDeliveryAgentDto.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResHubDeliveryAgentDto.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResRoleGetByIdDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/AuthConditionService.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/AuthConditionServiceImpl.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/AuthService.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/DeliveryAgentCacheService.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/DeliveryAgentService.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/DeliveryAgentServiceImpl.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/service/HubService.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/domain/common/IsAvailable.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/domain/common/Type.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/domain/common/UserRole.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/domain/entity/DeliveryAgent.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/domain/repository/DeliveryAgentRepository.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/domain/valueobject/Sequence.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/client/AuthClient.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/client/HubClient.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/config/ObjectMapperConfig.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/config/QueryDslConfig.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/config/RedisConfig.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/repository/DeliveryAgentJpaRepository.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/repository/DeliveryAgentQueryRepository.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/repository/DeliveryAgentQueryRepositoryImpl.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/infratructure/repository/DeliveryAgentRepositoryImpl.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/libs/dto/ExceptionResponseDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/libs/dto/SuccessResponseDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/libs/exception/ApiException.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/libs/exception/GlobalExceptionHandler.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/libs/message/ErrorMessage.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/presentation/controller/AgentController.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/presentation/dto/ReqDeliveryAgentPostDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/presentation/dto/ReqDeliveryAgentPutDTO.java
  com.first-class.msa.agent/src/main/resources/application.yml
Labels: 🌐 API, ✨ Feature

#35 업체 관리 서비스 코드 리팩토링
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/service/AuthService.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/service/BusinessService.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/service/HubService.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/client/AuthClient.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/infrastructure/client/HubClient.java
Labels: 🔨 Refactor

#37 허브 이동 정보 생성 및 최적 경로 조회 기능 구현
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/transit/HubNode.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/transit/ResHubTransitInfoGetDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/transit/ResHubTransitInfoPostDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubTransitInfoService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/model/HubTransitInfo.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/repository/HubTransitInfoRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubTransitInfo/HubTransitInfoRepositoryImpl.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubTransitInfo/JpaHubTransitInfoRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubTransitInfoController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/external/ExternalHubTransitInfoController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/request/transit/ReqHubTransitInfoPostDTO.java
Labels: 🌐 API, ✨ Feature

#41 허브 간 이동정보 수정 및 삭제 기능 구현
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/SuccessResponseDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/external/ExternalResHubGetByIdDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/dto/external/ExternalResRoleGetByUserIdDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/AuthService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubTransitInfoService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/repository/HubTransitInfoRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/client/AuthClient.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubTransitInfo/HubTransitInfoRepositoryImpl.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/infrastructure/repository/HubTransitInfo/JpaHubTransitInfoRepository.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubTransitInfoController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/external/ExternalHubController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/request/transit/ReqHubTransitInfoPutByIdDTO.java
Labels: ✨ Feature

#44 Global Exception 예외 처리 구현
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/global/exception/custom/AuthorityException.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/global/exception/custom/BadRequestException.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/global/exception/custom/EntityAlreadyExistException.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/global/exception/custom/ExceptionResponseDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/global/exception/handler/GlobalExceptionHandler.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/global/success/SuccessResponseDTO.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/application/service/BusinessService.java
  com.first-class.msa.business/src/main/java/com/first_class/msa/business/presentation/controller/BusinessController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/global/exception/custom/AuthorityException.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/global/exception/custom/BadRequestException.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/global/exception/custom/EntityAlreadyExistException.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/global/exception/custom/ExceptionResponseDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/global/exception/handler/GlobalExceptionHandler.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/global/success/SuccessResponseDTO.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/application/service/HubTransitInfoService.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/domain/model/Hub.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubController.java
  com.first-class.msa.hub/src/main/java/com/first_class/msa/hub/presentation/controller/HubTransitInfoController.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/global/exception/custom/AuthorityException.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/global/exception/custom/BadRequestException.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/global/exception/custom/EntityAlreadyExistException.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/global/exception/custom/ExceptionResponseDTO.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/global/exception/handler/GlobalExceptionHandler.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/global/success/SuccessResponseDTO.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/application/service/ProductService.java
  com.first-class.msa.product/src/main/java/com/first_class/msa/product/presentation/controller/ProductController.java
Labels: ✨ Feature

#52 [ FEAT ] 슬랙 메세지 생성,수정,삭제 및 ai 연동 ( #51 )
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ReqGeminiDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ReqMessagePostDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ReqMessageUpdateDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ResGeminiDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ResHubTransitInfoGetDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ResMessageDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ResOrderGetDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ResProductGetDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/dto/ResUserGetByIdDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/AiMessageService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/HubService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/MessageService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/OrderService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/ProductService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/SlackIntegrationService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/application/service/SlackMessageService.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/domain/model/Message.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/client/GeminiApiClient.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/client/HubClient.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/client/OrderClient.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/client/ProductClient.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/client/SlackApiClient.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/client/UserClient.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/configuration/RestTemplateConfig.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/infrastructure/repository/MessageRepository.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/libs/dto/ExceptionResponseDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/libs/dto/SuccessResponseDTO.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/libs/exception/ApiException.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/libs/exception/GlobalExceptionHandler.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/libs/message/ErrorMessage.java
  com.first-class.msa.message/src/main/java/com/first_class/msa/message/presentation/MessageController.java
  com.first-class.msa.message/src/main/resources/application.yml
Labels: ✨ Feature

#58 불필요한 DTO 정리 및 엔드포인트 수정 + README 추가
  README.md
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/application/dto/ResDTO.java
  com.first-class.msa.agent/src/main/java/com/first_class/msa/agent/presentation/controller/AgentController.java
  com.first-class.msa.orders/src/main/java/com/first_class/msa/orders/application/dto/ResDTO.java
  com.first-class.msa.orders/src/main/java/com/first_class/msa/orders/presentation/controller/OrderController.java
Labels: 🔨 Refactor, 📃 Docs
